USE SCHEMA HOL_SEC.INCIDENTE;
ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = LARGE;
USE WAREHOUSE HOL_WH;

-- ================= AUTH_LOGINS 20M (pais fijo por usuario) =================
CREATE OR REPLACE TABLE AUTH_LOGINS AS
WITH base AS (
  SELECT SEQ8() AS event_id,
         UNIFORM(1,300,RANDOM()) AS uidx,
         DATEADD('minute', -UNIFORM(0, 86400, RANDOM()), CURRENT_TIMESTAMP()) AS event_ts,
         IFF(UNIFORM(1,100,RANDOM())<=12,'FAIL','SUCCESS') AS status,
         UNIFORM(1,255,RANDOM()) AS o1, UNIFORM(1,255,RANDOM()) AS o2,
         UNIFORM(1,255,RANDOM()) AS o3, UNIFORM(1,255,RANDOM()) AS o4
  FROM TABLE(GENERATOR(ROWCOUNT=>20000000))
)
SELECT event_id::NUMBER AS event_id,
       event_ts,
       'usr_'||LPAD(uidx,3,'0') AS user_name,
       ARRAY_CONSTRUCT('Bogota','Medellin','Lima','Madrid','Miami','Frankfurt','Singapore')[MOD(uidx,7)]::STRING AS city,
       ARRAY_CONSTRUCT('CO','CO','PE','ES','US','DE','SG')[MOD(uidx,7)]::STRING AS country,
       o1||'.'||o2||'.'||o3||'.'||o4 AS client_ip,
       status
FROM base;

-- svc_etl: base CO
INSERT INTO AUTH_LOGINS
SELECT 900000+SEQ8(), DATEADD('minute', -UNIFORM(2880,86400,RANDOM()), CURRENT_TIMESTAMP()),
       'svc_etl','Bogota','CO','10.0.0.5','SUCCESS'
FROM TABLE(GENERATOR(ROWCOUNT=>200));

-- svc_etl: rafaga de fallos ~02:00 ayer
INSERT INTO AUTH_LOGINS
SELECT 901000+SEQ8(),
       DATEADD('second', SEQ8()*3, DATEADD('hour', 2, DATEADD('day',-1,DATE_TRUNC('day',CURRENT_TIMESTAMP())))),
       'svc_etl','Bogota','CO','10.0.0.5','FAIL'
FROM TABLE(GENERATOR(ROWCOUNT=>40));

-- svc_etl: viaje imposible CO 00:30 -> DE 02:30 ayer
INSERT INTO AUTH_LOGINS VALUES
 (902000, DATEADD('minute', 30,  DATEADD('day',-1,DATE_TRUNC('day',CURRENT_TIMESTAMP()))),'svc_etl','Bogota','CO','10.0.0.5','SUCCESS'),
 (902001, DATEADD('minute', 150, DATEADD('day',-1,DATE_TRUNC('day',CURRENT_TIMESTAMP()))),'svc_etl','Frankfurt','DE','185.22.14.9','SUCCESS');

-- ================= EXPORT_EVENTS 25M =================
CREATE OR REPLACE TABLE EXPORT_EVENTS AS
SELECT SEQ8()::NUMBER AS export_id,
       DATEADD('minute', -UNIFORM(0,86400,RANDOM()), CURRENT_TIMESTAMP()) AS export_ts,
       'usr_'||LPAD(UNIFORM(1,300,RANDOM()),3,'0') AS user_name,
       UNIFORM(50000,5000000,RANDOM())::NUMBER AS bytes_out
FROM TABLE(GENERATOR(ROWCOUNT=>25000000));

-- svc_etl: base pequena
INSERT INTO EXPORT_EVENTS
SELECT 700000+SEQ8(), DATEADD('minute', -UNIFORM(2880,86400,RANDOM()), CURRENT_TIMESTAMP()),
       'svc_etl', UNIFORM(50000,2000000,RANDOM())
FROM TABLE(GENERATOR(ROWCOUNT=>1000));

-- svc_etl: pico de exfiltracion 03:00 ayer
INSERT INTO EXPORT_EVENTS
SELECT 701000+SEQ8(),
       DATEADD('minute', SEQ8()*2, DATEADD('hour', 3, DATEADD('day',-1,DATE_TRUNC('day',CURRENT_TIMESTAMP())))),
       'svc_etl', UNIFORM(180000000,400000000,RANDOM())
FROM TABLE(GENERATOR(ROWCOUNT=>30));

-- ================= CUSTOMERS 5M =================
CREATE OR REPLACE TABLE CUSTOMERS AS
SELECT SEQ8()::NUMBER AS customer_id,
       'Cliente '||SEQ8() AS full_name,
       'user'||SEQ8()||'@correo.com' AS email,
       LPAD(UNIFORM(1000000000,9999999999,RANDOM()),10,'0') AS national_id,
       '****-****-****-'||LPAD(UNIFORM(0,9999,RANDOM()),4,'0') AS card_last4,
       ARRAY_CONSTRUCT('Bogota','Medellin','Cali','Barranquilla')[UNIFORM(0,3,RANDOM())]::STRING AS branch_city
FROM TABLE(GENERATOR(ROWCOUNT=>5000000));

-- ================= UNLOAD a S3 =================
COPY INTO @stg_hol/auth_logins/data_ FROM AUTH_LOGINS
  FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=';' COMPRESSION=GZIP) HEADER=TRUE MAX_FILE_SIZE=100000000 OVERWRITE=TRUE;
COPY INTO @stg_hol/export_events/data_ FROM EXPORT_EVENTS
  FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=';' COMPRESSION=GZIP) HEADER=TRUE MAX_FILE_SIZE=50000000 OVERWRITE=TRUE;
COPY INTO @stg_hol/customers/data_ FROM CUSTOMERS
  FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=';' COMPRESSION=GZIP) HEADER=TRUE MAX_FILE_SIZE=100000000 OVERWRITE=TRUE;

SELECT 'AUTH_LOGINS' AS tabla, COUNT(*) AS filas FROM AUTH_LOGINS
UNION ALL SELECT 'EXPORT_EVENTS', COUNT(*) FROM EXPORT_EVENTS
UNION ALL SELECT 'CUSTOMERS', COUNT(*) FROM CUSTOMERS;
